#!/bin/bash

if ! [ -n "$1" ]; then
    echo 'Error: extension name as param is needed (e.g. "tileserver")' >&2
    exit 1
fi

if ! [ -f "extensions/$1/docker-compose.yml" ]; then
	echo "Error: extension '$1' seems not to be added/activated because the 'docker-compose.yml' is missing" >&2
	exit 1
fi

echo "(re)starting extension '$1' ..."
sudo docker-compose -f "./extensions/$1/docker-compose.yml" up --detach
exitcode=$?
if ! [ $exitcode -eq 0 ]; then
	echo "Error: something has gone wrong and exited with code '$exitcode'" >&2
	exit $exitcode
else
	echo "extension '$1' (re)started!"
	exit 0
fi
