version: '3'
services:
  map_builder:
    image: map_builder
    build: .
    environment: 
      - city=$city
      - bbox=$bbox
    volumes:
      - ../data/$city/static_maps/static-maps:/app/out
    depends_on:
      tileserver:
        condition: service_healthy

  tileserver:
    image: maptiler/tileserver-gl
    command: --port 8080 --config /config/config.json --verbose
    volumes:
      - "./config:/config"
      - "../data/$city/tileserver/region:/region"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health"]
        interval: 5s
        timeout: 2s
        retries: 20
    
  #tileserver:
    #image: klokantech/tileserver-gl
    #volumes:
      #- ../map-data-builder/data/$city:/data # TODO: need to make this work again
    #healthcheck:
        #test: ["CMD", "curl", "-f", "http://localhost/health"]
        #interval: 5s
        #timeout: 2s
        #retries: 20
