version: '3'
services:
  tileserver:
    image: maptiler/tileserver-gl
    command: --port 8080 --config /config/config.json --verbose
    ports:
      - "8002:8080"
    volumes:
      - "./data:/data"
      - "./config:/config"
    restart: unless-stopped
    logging:
      driver: "journald"
      options:
        tag: "{{.Name}}"

networks:
  default:
    name: trufi-server
