version: '3'
services:
  otp:
    build:
      context: ./$otpversion
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8080"
    restart: unless-stopped
    volumes: 
      - ./otp/data:/app/graphs
    logging:
      driver: "journald"
      options:
        tag: "{{.Name}}"
      
networks:
  default:
    name: trufi-server
